services:
  db:
    image: postgres
    container_name: ontapapprg-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
      - ./beers_db_new.backup:/var/lib/postgresql/beers_db_new.backup
    networks:
      - ontapapprg-net
  
  pgweb:
    image: sosedoff/pgweb:latest
    container_name: ontapapprg-pgweb
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8085:8081"
    depends_on:
      - db
    networks:
      - ontapapprg-net


networks:
  ontapapprg-net:
    driver: bridge